# s1=input('enter the first sting :')
# s2=input('enter the secound string :')
# # s1='damodara'
# # s2='santosh'
# i,j=0,0
# # output=''
# # while i<len(s1) or j<len(s2):
# #     if i<len(s1):
# #         output=output+s1[i]
# #         i=i+1
# #     if j<len(s2):
# #         output=output+s2[j]
# #         j=j+1
# # print(output)

# s= input('enter the mixed string :')
# s1=s2=' '
# for x in s:
#     if x.isalpha():
#         s1=s1+x
#     else:
#         s2=s2+x
# # print(s1)
# # print(s2)

# output=''.join(sorted(s1)+sorted(s2))
# print(output)

# for x in sorted(s1):
#     output=output+x
# for x in sorted(s2):
#     output=output+x
# print(output)

# s=input('enter any string')
# output=''
# for x in s:
#     if x.isalpha():
#       ch=x
#     else:
#         output=output+ch*int(x)
# print(output)
    
    
# t=input('enter any text :')
# output=''
# num=''
# i=0
# while i<len(t):
#     if t[i].isalpha():
#         ch=t[i]
#     else:
#         num=num+t[i]
#         if i==len(t)-1:
#             output=output+ch*int(num)
#         if i+1<len(t) and t[i+1].isalpha():
#             output=output+ch*int(num)
#             num=''
#     i=i+1
# print(output)
    
    

# a='a3f5s4'
# output=''

# for i in a:
#     if i.isalpha():
#         ch=i
#         output=output+ch
#     else:
#         newch=chr(ord(ch)+int(i))
#         output=output+newch
# print(output)

# print(ord('a'))
# print(chr(98))

# s='aaaaaaaaaaabbbbbbbbcccccccdddddddfffffffgggg'
# l=[]
# for x in s:
#     if x not in l:
#         l.append(x)
# output=''.join(l)
# print(output)




# s=int(input('enter any string :'))
# r=reversed(s)
# output=''.join(s)
# print(output)

# s=s=int(input('enter any string :'))
# i=len(s)-1
# target=''
# while i>=0:
#     target=target+s[i]
# print(target)

# number=12345
# reversed_number=reversed_number(number)
# print(reversed_number)


# n=123
# revs_number=0
# while n!=0:
#     remainer=n %10
#     revs_number=(revs_number*10)+remainer
#     n//=10
# print=("revrese_number :",str(revs_number))


# num = 1234
# reversed_num = 0

# while num != 0:
#     digit = num % 10
#     reversed_num = reversed_num * 10 + digit
#     num //= 10

# print("Reversed Number: " + str(reversed_num))




# santosh.d3657
